http:
  routers:
    ft991a:
      rule: "Host(`{{ env \"RADIO_HOSTNAME\" }}`)"
      entryPoints:
        - websecure
      service: ft991a
      tls: {}

    ft991a-ws:
      rule: "Host(`{{ env \"RADIO_HOSTNAME\" }}`) && PathPrefix(`/ws`)"
      entryPoints:
        - websecure
      service: ft991a
      tls: {}

  services:
    ft991a:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:{{ env \"RADIO_BACKEND_PORT\" }}"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/cert.crt
        keyFile: /etc/traefik/certs/cert.key
